### ISSUE TITLE
Scroll and drag problem

### ISSUE THREAD

**Issue by Monabr** [MohamedRejeb/compose-dnd#11]
Hi. You have a great library here!

I found a problem with the animation of the reordering in the list and possibly an incorrect position calculation. This happens when the list is scrollable. Please watch the attached video.

You can see 2 problems:

1) When I take the first element and start to drag it down - it does not drag, but the list suddenly scrolls.

2) When I take an element from the middle of the list and drag it up - the list does not scroll up.

https://github.com/MohamedRejeb/compose-dnd/assets/30532666/5cf12ea4-0f1b-4457-a578-8577e0a62957

**Comment by MohamedRejeb** [comment]
Feel free to reopen if you still have an issue.
