### ISSUE TITLE
 Unresolved reference to com.mohamedrejeb

### ISSUE THREAD

**Issue by islamYMansour** [MohamedRejeb/compose-dnd#12]
Description

I'm trying to use the compose-dnd library in my project which is java project and  I make an upgrade for some screens using jetcompose, but I'm encountering an unresolved reference issue when attempting to import the library.

Steps to Reproduce
Added the following dependency to build.gradle:

groovy
 ``` 
implementation 'com.mohamedrejeb.dnd:compose-dnd:0.2.0'
```

Tried to import the library in my Kotlin file:

```
import com.mohamedrejeb.compose.dnd.annotation.ExperimentalDndApi
import com.mohamedrejeb.compose.dnd.drop.dropTarget
import com.mohamedrejeb.compose.dnd.reorder.ReorderContainer
import com.mohamedrejeb.compose.dnd.reorder.ReorderableItem
```

I receive an unresolved reference error for mohamedrejeb

Additional Information
Android Studio version: Android Studio Electric Eel | 2022.1.1
Kotlin version: 1.7.9
Compose version: 1.2.0

Could you please provide guidance on resolving this issue or update the documentation with the correct usage instructions?

Thank you!

**Comment by MohamedRejeb** [comment]
Make sure that you have `mavenCentral()` here: https://github.com/MohamedRejeb/compose-dnd/blob/15c8c9582e62fba59c87dab3904c66920096547c/settings.gradle.kts#L18

**Comment by islamYMansour** [comment]
@MohamedRejeb 
could you give me a sample for ordering like Kanaban board?

**Comment by MohamedRejeb** [comment]
You can check the reorder sample:
https://github.com/MohamedRejeb/compose-dnd/blob/main/sample/common/src/commonMain/kotlin/ui/ReorderListScreen.kt
