### ISSUE TITLE
Modifier.animateItem()

### ISSUE THREAD

**Issue by rrocav3** [MohamedRejeb/compose-dnd#15]
Hello and thank you so much for the library!

I would like implement the library along with `Modifier.animateItem()` which in first place is doing good job with recolocating the items on the lists but I don't know why is crashing internally depending on how you drag/drop items:

```positioning a list item with non zero crossAxisOffset is not supported```

I based my code on that sample: https://github.com/MohamedRejeb/compose-dnd/blob/main/sample/common/src/commonMain/kotlin/ui/ListToListWithReorderScreen.kt

Is there a way to fix that? Thank you so much!

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for opening this issue. I will check it and get back to you.

**Comment by rrocav3** [comment]
Hello again, could you see anything on that? Can I contribute on that in some way? Thanks in advance

**Comment by MohamedRejeb** [comment]
Can you share the Kotlin and Compose version you are using.
It looks like it's because you are using Compose 1.7 and the library is using Compose 1.6

**Comment by rrocav3** [comment]
Yes I'm using compose 1.7, I cannot downgrade since I'm using libraries which depend on that.

I'm planning to move to stable version in long term but it will be cool if there could be library versions for unstable versions since KMP is very changing and some alpha/betas of compose compiler include some important features.

**Comment by MohamedRejeb** [comment]
I see, I will publish a new version using Compose 1.7 in the next few days

**Comment by rrocav3** [comment]
Seems like this is fixed in compose stable 1.7
